'use client';

import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

type ContentType = 'DESIGN_ASSET' | 'AI_SKILL' | 'AI_CASE' | 'AI_PROJECT';
type Body = Record<string, unknown>;
const value = (body: Body | undefined, key: string) => typeof body?.[key] === 'string' ? body[key] as string : '';
const list = (body: Body | undefined, key: string) => Array.isArray(body?.[key]) ? (body[key] as unknown[]).filter((entry): entry is string => typeof entry === 'string').join('\n') : '';

function Field({ label, name, defaultValue = '', placeholder, multiline = false, required = true }: { label: string; name: string; defaultValue?: string; placeholder?: string; multiline?: boolean; required?: boolean }) {
  return <label className="grid gap-2 rounded-[16px] border border-white/[.1] bg-black/15 p-3.5 text-sm font-medium text-white/75"><span>{label}{required ? <span className="ml-1 text-red-300">*</span> : null}</span>{multiline ? <Textarea className="min-h-24 border-white/[.12] bg-black/30 text-white placeholder:text-white/35" defaultValue={defaultValue} name={name} placeholder={placeholder} /> : <Input className="h-11 border-white/[.12] bg-black/30 text-white placeholder:text-white/35" defaultValue={defaultValue} name={name} placeholder={placeholder} />}</label>;
}

function Choice({ label, name, defaultValue, options }: { label: string; name: string; defaultValue: string; options: Array<[string, string]> }) {
  return <label className="grid gap-2 rounded-[16px] border border-white/[.1] bg-black/15 p-3.5 text-sm font-medium text-white/75"><span>{label}<span className="ml-1 text-red-300">*</span></span><select className="h-11 rounded-md border border-white/[.12] bg-black/30 px-3 text-white" defaultValue={defaultValue} name={name}><option value="">请选择</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>;
}

export function ContentTypeFields({ contentType, body }: { contentType: ContentType; body?: Body }) {
  const sectionClass = 'grid gap-4 border-t border-white/[.1] pt-6';
  const heading = (eyebrow: string, title: string) => <div><p className="text-[11px] font-bold tracking-[.14em] text-white/45">{eyebrow}</p><h2 className="mt-1 text-[25px] font-semibold tracking-[-.04em] text-white">{title}</h2><p className="mt-2 text-xs text-white/45"><span className="text-red-300">*</span> 为提交审核前必须完整的字段</p></div>;
  if (contentType === 'DESIGN_ASSET') return <section className={sectionClass}>{heading('ASSET DEFINITION', '设计资产信息')}<div className="grid gap-4 md:grid-cols-2"><Field label="资产类型" name="assetType" defaultValue={value(body, 'assetType')} placeholder="例如：组件规范、研究模板" /><Field label="适用平台（每行一个）" name="platforms" defaultValue={list(body, 'platforms')} placeholder="iOS\nAndroid\nWeb" multiline /></div><Field label="适用场景（每行一个）" name="scenarios" defaultValue={list(body, 'scenarios')} multiline /><Field label="不适用场景（每行一个）" name="unsuitableScenarios" defaultValue={list(body, 'unsuitableScenarios')} multiline /><Field label="解决的问题" name="problemStatement" defaultValue={value(body, 'problemStatement')} multiline /><Field label="使用指引" name="usageGuide" defaultValue={value(body, 'usageGuide')} placeholder="说明步骤、前置条件和注意事项" multiline /><Field label="资源链接（每行一个）" name="resourceLinks" defaultValue={list(body, 'resourceLinks')} placeholder="https://..." multiline /><Field label="相关资产 ID（每行一个）" name="relatedAssetIds" defaultValue={list(body, 'relatedAssetIds')} multiline required={false} /></section>;
  if (contentType === 'AI_SKILL') return <section className={sectionClass}>{heading('REUSABLE METHOD', 'AI Skill 信息')}<Field label="Skill 目标" name="goal" defaultValue={value(body, 'goal')} multiline /><Field label="适用场景（每行一个）" name="scenarios" defaultValue={list(body, 'scenarios')} multiline /><Field label="不适用场景（每行一个）" name="unsuitableScenarios" defaultValue={list(body, 'unsuitableScenarios')} multiline /><Field label="适用角色（每行一个）" name="applicableRoles" defaultValue={list(body, 'applicableRoles')} multiline /><Field label="输入要求" name="inputRequirements" defaultValue={value(body, 'inputRequirements')} multiline /><Field label="输出结构" name="outputSchema" defaultValue={value(body, 'outputSchema')} multiline /><Field label="核心 Prompt" name="promptTemplate" defaultValue={value(body, 'promptTemplate') || value(body, 'prompt')} multiline /><Field label="执行步骤" name="executionSteps" defaultValue={value(body, 'executionSteps') || list(body, 'steps')} multiline /><div className="grid gap-4 md:grid-cols-2"><Field label="示例输入" name="exampleInput" defaultValue={value(body, 'exampleInput')} multiline /><Field label="示例输出" name="exampleOutput" defaultValue={value(body, 'exampleOutput')} multiline /></div><Field label="人工复核规则" name="humanReviewRules" defaultValue={value(body, 'humanReviewRules')} multiline /><Field label="已知限制与风险" name="limitations" defaultValue={value(body, 'limitations')} multiline /><Field label="推荐模型（每行一个）" name="recommendedModels" defaultValue={list(body, 'recommendedModels')} multiline /><div className="grid gap-4 md:grid-cols-2"><Choice label="数据安全等级" name="dataSecurityLevel" defaultValue={value(body, 'dataSecurityLevel')} options={[["public", "公开"], ["internal", "内部"], ["confidential", "机密"]]} /><Field label="Prompt 版本" name="promptVersion" defaultValue={value(body, 'promptVersion')} placeholder="例如：1.0" /></div></section>;
  if (contentType === 'AI_CASE') return <section className={sectionClass}>{heading('PRACTICE EVIDENCE', 'AI 案例信息')}<Field label="案例背景" name="background" defaultValue={value(body, 'background')} multiline /><Field label="原始问题" name="originalProblem" defaultValue={value(body, 'originalProblem')} multiline /><Field label="原有流程" name="originalProcess" defaultValue={value(body, 'originalProcess')} multiline /><Field label="AI 介入节点" name="aiIntervention" defaultValue={value(body, 'aiIntervention')} multiline /><Field label="AI 完成内容" name="aiResponsibilities" defaultValue={value(body, 'aiResponsibilities')} multiline /><Field label="设计师判断内容" name="humanResponsibilities" defaultValue={value(body, 'humanResponsibilities')} multiline /><Field label="最终结果" name="resultSummary" defaultValue={value(body, 'resultSummary')} multiline /><Field label="前后对比" name="beforeAfterComparison" defaultValue={value(body, 'beforeAfterComparison')} multiline /><div className="grid gap-4 md:grid-cols-2"><Field label="样本范围" name="sampleSize" defaultValue={value(body, 'sampleSize')} /><Field label="验证方式" name="validationMethod" defaultValue={value(body, 'validationMethod')} /></div><Field label="数据结果" name="dataResult" defaultValue={value(body, 'dataResult')} multiline /><Field label="局限性" name="limitations" defaultValue={value(body, 'limitations')} multiline /><Field label="可复用结论" name="reusableConclusion" defaultValue={value(body, 'reusableConclusion')} multiline /><div className="grid gap-4 md:grid-cols-2"><Field label="关联 Skill 内容 ID" name="relatedSkillContentId" defaultValue={value(body, 'relatedSkillContentId')} required={false} /><Field label="关联项目内容 ID" name="relatedProjectContentId" defaultValue={value(body, 'relatedProjectContentId')} required={false} /></div></section>;
  return <section className={sectionClass}>{heading('PROJECT BRIEF', 'AI 项目信息')}<div className="grid gap-4 md:grid-cols-2"><Field label="项目编号" name="projectCode" defaultValue={value(body, 'projectCode')} placeholder="例如：P27" /><Field label="所属领域" name="domain" defaultValue={value(body, 'domain')} /></div><Field label="目标价值" name="targetValue" defaultValue={value(body, 'targetValue')} multiline /><div className="grid gap-4 md:grid-cols-2"><Choice label="当前阶段" name="projectStage" defaultValue={value(body, 'projectStage')} options={[["EXPLORING", "探索方案"], ["PENDING_EVALUATION", "待评估"], ["READY", "可立项"], ["PILOTING", "试点中"], ["VERIFIED", "已验证"], ["PAUSED", "暂缓"], ["TERMINATED", "终止"]]} /><Choice label="优先级" name="priority" defaultValue={value(body, 'priority')} options={[["high", "高"], ["medium", "中"], ["low", "低"]]} /></div><Field label="问题陈述" name="problemStatement" defaultValue={value(body, 'problemStatement')} multiline /><Field label="解决方案假设" name="solutionHypothesis" defaultValue={value(body, 'solutionHypothesis')} multiline /><Field label="预期效果" name="expectedOutcome" defaultValue={value(body, 'expectedOutcome')} multiline /><Field label="风险" name="riskLevel" defaultValue={value(body, 'riskLevel')} multiline /><Field label="评估结论" name="evaluationResult" defaultValue={value(body, 'evaluationResult')} multiline /><div className="grid gap-4 md:grid-cols-2"><Field label="关联 Skill ID（每行一个）" name="relatedSkillIds" defaultValue={list(body, 'relatedSkillIds')} multiline required={false} /><Field label="关联案例 ID（每行一个）" name="relatedCaseIds" defaultValue={list(body, 'relatedCaseIds')} multiline required={false} /></div><Field label="外部正式项目引用" name="convertedProjectRef" defaultValue={value(body, 'convertedProjectRef')} required={false} /></section>;
}
